import fnmatch
import os
import re
from pathlib import Path

RULES = {
    "vivado": [
        ("<P>.xpr", "EVIDENCE", "project file: file lists, properties, run settings"),
        ("*.bit", "EVIDENCE", "bitstream"),
        ("*.msk", "EVIDENCE", "readback mask written with the bitstream"),
        ("reports/*.rpt", "EVIDENCE", "signoff reports"),
        ("<P>.runs/*/runme.log", "EVIDENCE", "run log: tool version, licenses"),
        ("<P>.runs/*.vds", "EVIDENCE", "synthesis log"),
        ("<P>.runs/*.vdi", "EVIDENCE", "implementation log"),
        ("<P>.runs/synth_1/*.dcp", "EVIDENCE", "synthesized netlist"),
        ("<P>.runs/*_routed.dcp", "EVIDENCE", "routed checkpoint"),
        ("<P>.runs/*", "BYPRODUCT", "run directory: scripts, journals, progress files, and reports the run writes"),
        ("<P>.cache/*", "BYPRODUCT", "IP and Web-Talk cache the tool rebuilds"),
        ("<P>.gen/*", "BYPRODUCT", "IP and block-design output products regenerated from the approved .xci/.bd"),
        ("<P>.ip_user_files/*", "BYPRODUCT", "IP simulation and user files regenerated by the tool"),
        ("<P>.sim/*", "BYPRODUCT", "simulation run directory"),
        ("<P>.hw/*", "BYPRODUCT", "hardware-manager settings"),
        ("<P>.srcs/sources_1/bd/*.bda", "BYPRODUCT", "block-design accessory file written when the .bd is saved"),
        ("<P>.srcs/sources_1/bd/*/ip/*/*.xci", "BYPRODUCT", "block-design cell configuration; its digest is part of the .bd evidence"),
    ],
    "quartus": [
        ("*.qsf", "EVIDENCE", "project settings: file list, assignments, options"),
        ("*.qpf", "EVIDENCE", "project file"),
        ("*.sof", "EVIDENCE", "SRAM object file"),
        ("*.jic", "EVIDENCE", "configuration-flash image"),
        ("*.rpt", "EVIDENCE", "compilation reports"),
        ("output_files/*.rpt", "EVIDENCE", "compilation reports"),
        ("db/*.map.cdb", "EVIDENCE", "synthesized netlist"),
        ("db/*.cmp.cdb", "EVIDENCE", "fitted netlist"),
        ("db/*", "BYPRODUCT", "compilation database"),
        ("incremental_db/*", "BYPRODUCT", "incremental compilation database"),
        ("*.summary", "BYPRODUCT", "report summaries (the full reports are evidence)"),
        ("*.smsg", "BYPRODUCT", "suppressed-message list"),
        ("*.done", "BYPRODUCT", "compilation time stamp"),
        ("*.jdi", "BYPRODUCT", "JTAG debug information"),
        ("*.sld", "BYPRODUCT", "debug-node list"),
        ("*.pin", "BYPRODUCT", "pin report written from the assignments"),
    ],
    "libero": [
        ("*.prjx", "EVIDENCE", "project file: file lists and tool associations"),
        ("tooldata/*_tools.xml", "EVIDENCE", "tool options"),
        ("synthesis/*.srr", "EVIDENCE", "synthesis report and log"),
        ("synthesis/synplify.log", "EVIDENCE", "synthesis log: licenses"),
        ("synthesis/*.vm", "EVIDENCE", "synthesized netlist"),
        ("synthesis/*.srm", "EVIDENCE", "synthesized netlist"),
        ("designer/*/*.adl", "EVIDENCE", "place-and-route database"),
        ("designer/*/*_has_violations", "EVIDENCE", "timing status"),
        ("designer/*/*_timing_multi_corner.xml", "EVIDENCE", "timing report"),
        ("designer/*/*_compile_netlist_resources.rpt", "EVIDENCE", "resource report"),
        ("export/*.job", "EVIDENCE", "programming job"),
        ("export/*.digest", "EVIDENCE", "configuration digests of the programming job"),
        ("designer/*", "BYPRODUCT", "place-and-route and programming-data working files"),
        ("synthesis/*", "BYPRODUCT", "synthesis working files"),
        ("simulation/*", "BYPRODUCT", "simulation files the tool generates"),
        ("stimulus/*", "BYPRODUCT", "testbench folder (simulation only)"),
        ("smartgen/*", "BYPRODUCT", "core generator working files"),
        ("viewdraw/*", "BYPRODUCT", "schematic viewer settings"),
        ("tooldata/*", "BYPRODUCT", "tool logs and messages"),
        ("export/*", "BYPRODUCT", "exported programming files other than the job"),
        ("component/Actel/*", "BYPRODUCT", "core definitions copied from the vault"),
        ("component/Microchip/*", "BYPRODUCT", "core definitions copied from the vault"),
        ("component/Microsemi/*", "BYPRODUCT", "core definitions copied from the vault"),
        ("component/User/*", "BYPRODUCT", "user-core catalog entries"),
        ("component/*.v", "BYPRODUCT", "synthesis component library generated by Libero"),
        ("component/work/*/*.sdb", "BYPRODUCT", "SmartDesign database; the generated netlist is evidence"),
        ("component/work/*.v", "BYPRODUCT", "HDL generated from a component configuration"),
        ("component/work/*.vhd", "BYPRODUCT", "HDL generated from a component configuration"),
        ("component/work/*.sdc", "BYPRODUCT", "constraints generated from a component configuration"),
        ("component/work/*.tcl", "BYPRODUCT", "generator scripts"),
        ("component/work/*.xml", "BYPRODUCT", "generator metadata"),
        ("component/work/*.html", "BYPRODUCT", "generator reports"),
        ("component/work/*.log", "BYPRODUCT", "generator logs"),
        ("component/work/*.txt", "BYPRODUCT", "generator manifests"),
        ("component/work/*.xsl", "BYPRODUCT", "report style sheets"),
        ("component/work/*.bfm", "BYPRODUCT", "simulation bus-functional models"),
        ("component/work/*.do", "BYPRODUCT", "simulation scripts"),
        ("component/work/*.gen", "BYPRODUCT", "generator state"),
        ("component/work/*.mem", "BYPRODUCT", "simulation memory images generated for a core"),
        ("constraint/*_derived_constraints.sdc", "BYPRODUCT", "constraints Libero derives from the IP configuration"),
        ("constraint/*_sdc_errors.log", "BYPRODUCT", "constraint-check logs"),
        ("constraint/run_tao_ag.tcl", "BYPRODUCT", "timing-constraint generation script written by Libero"),
        ("libero_setup_info.txt", "BYPRODUCT", "installation summary written with the project"),
    ],
    "openxc7": [
        ("synth.ys", "EVIDENCE", "synthesis script: sources and options"),
        ("pnr.args", "EVIDENCE", "place-and-route arguments"),
        ("yosys.log", "EVIDENCE", "synthesis log"),
        ("nextpnr.log", "EVIDENCE", "place-and-route log"),
        ("build.log", "EVIDENCE", "flow log"),
        ("design.json", "EVIDENCE", "synthesized netlist"),
        ("routed.json", "EVIDENCE", "routed design"),
        ("report.json", "EVIDENCE", "timing and utilization report"),
        ("*.bit", "EVIDENCE", "bitstream"),
        ("*.fasm", "BYPRODUCT", "intermediate configuration features, rewritten into the bitstream"),
        ("*.frames", "BYPRODUCT", "intermediate configuration frames, rewritten into the bitstream"),
    ],
}
OWN = ("_ev.json",)


def _match(rel: str, pattern: str, project: str) -> bool:
    return fnmatch.fnmatchcase(rel.lower(), pattern.replace("<P>", project).lower())


def generated(build: Path, flow: str, project: str, path: Path) -> bool:
    build, path = Path(build).resolve(), Path(path).resolve()
    if not path.is_relative_to(build):
        return False
    rel = path.relative_to(build).as_posix()
    return any(_match(rel, pat, project) for pat, cls, _ in RULES[flow] if cls == "BYPRODUCT")


def account(build: Path, flow: str, project: str, inputs) -> list:
    build = Path(build).resolve()
    known = {r.relative_to(build).as_posix().lower() for r in (Path(p).resolve() for p in inputs)
             if r.is_relative_to(build)}
    base, out = len(str(build)) + 1, []
    for root, _, files in os.walk(build):
        for f in files:
            rel = os.path.join(root, f)[base:].replace("\\", "/")
            if f in OWN or rel.lower() in known:
                continue
            if not any(_match(rel, pat, project) for pat, _, _ in RULES[flow]):
                out.append(rel)
    return sorted(out)


VERILOG = (".v", ".sv", ".vh", ".svh")
VHDL = (".vhd", ".vhdl")
_ARG = r'(?:"([^"]+)"|`?(\w+))'
_REFS = {
    VERILOG: [("inc", re.compile(r'^\s*`include\s+' + _ARG, re.M)),
              ("data", re.compile(r'\$readmem[hb]\s*\(\s*' + _ARG))],
    VHDL: [("data", re.compile(r'\bfile\s+\w+\s*:\s*\w+\s+(?:open\s+\w+\s+)?is\s+(?:in\s+)?' + _ARG, re.I)),
           ("data", re.compile(r'\bfile_open\s*\(\s*(?:\w+\s*,\s*)?\w+\s*,\s*' + _ARG, re.I))],
}
_BINDINGS = [re.compile(p, re.I) for p in (
    r'\b(\w+)\s*(?:\[[^\]]*\]\s*)?=\s*"([^"]+)"',
    r'\.(\w+)\s*\(\s*"([^"]+)"\s*\)',
    r'`define\s+(\w+)\s+"([^"]+)"',
    r'\b(\w+)\s*:\s*string\s*:=\s*"([^"]+)"',
    r'\b(\w+)\s*=>\s*"([^"]+)"')]
_COMMENTS = {VERILOG: [re.compile(r"//[^\n]*"), re.compile(r"/\*.*?\*/", re.S)], VHDL: [re.compile(r"--[^\n]*")]}


def _key(p):
    return os.path.normcase(os.path.abspath(p))


def moved(path, bases):
    path, parts = Path(path), Path(path).parts[1:]
    if path.is_file() and any(_key(path).startswith(_key(b) + os.sep) for b in bases):
        return path
    for i in range(len(parts)):
        for base in (b for d in map(Path, bases) for b in (d, *d.parents)):
            c = base / Path(*parts[i:])
            if c.is_file() and _key(c) != _key(path):
                return c
    return path


def _lang(path):
    return next((k for k in (VERILOG, VHDL) if Path(path).suffix.lower() in k), None)


def hdl_reads(sources, include_dirs=(), base_dirs=()):
    texts, todo = {}, [Path(s) for s in sources]
    found, missing = [], []
    while True:
        while todo:
            src = todo.pop()
            if src in texts or not src.is_file() or _lang(src) is None:
                continue
            text = src.read_text(encoding="utf-8", errors="ignore")
            for c in _COMMENTS[_lang(src)]:
                text = c.sub("", text)
            texts[src] = text
        values = {}
        for text in texts.values():
            for b in _BINDINGS:
                for name, value in b.findall(text):
                    values.setdefault(name.lower(), set()).add(value)
        found, missing, new = [], [], []
        for src, text in texts.items():
            for kind, rx in _REFS[_lang(src)]:
                for literal, name in rx.findall(text):
                    names = [literal] if literal else sorted(values.get(name.lower(), ()))
                    hits = []
                    for n in names:
                        ref = Path(n)
                        cands = [moved(ref, [src.parent, *base_dirs]), ref] if ref.is_absolute() else \
                            [d / ref for d in [src.parent, *map(Path, include_dirs), *map(Path, base_dirs)]]
                        hit = next((c for c in cands if c.is_file()), None)
                        if hit is not None:
                            hits.append(hit)
                    if not hits:
                        missing.append(f"{src.name}: {literal or name}")
                    for hit in hits:
                        if hit not in found:
                            found.append(hit)
                        if kind == "inc" and hit not in texts:
                            new.append(hit)
        if not new:
            return found, missing
        todo = new


_SOURCE = re.compile(r"^\s*source\s+(?:-\w+\s+)*(.+?)\s*(?:;\s*)?$", re.M)
_HERE = re.compile(r"^\[file\s+dirname\s+\[info\s+script\]\]/")


def tcl_sources(scripts, base_dirs=()):
    found, missing, todo, seen = [], [], [Path(s) for s in scripts], set()
    while todo:
        script = todo.pop()
        if script in seen or not script.is_file():
            continue
        seen.add(script)
        for arg in _SOURCE.findall(script.read_text(encoding="utf-8", errors="ignore")):
            arg = arg.strip("{}\"")
            rel = _HERE.sub("", arg)
            if "$" in rel or "[" in rel:
                missing.append(f"{script.name}: source {arg}")
                continue
            ref = Path(rel)
            cands = [moved(ref, [script.parent, *base_dirs]), ref] if ref.is_absolute() else \
                [script.parent / ref] + ([] if rel != arg else [Path(d) / ref for d in base_dirs])
            hit = next((c for c in cands if c.is_file()), None)
            if hit is None:
                missing.append(f"{script.name}: source {arg}")
            elif hit not in found:
                found.append(hit)
                todo.append(hit)
    return found, missing
