`timescale 1ns / 1ps
// Zybo Z7-20: AMD Clocking Wizard (MMCM), 125 MHz in -> 100 MHz / 75 MHz.
// clk_wiz_0 is generated by flows/vivado/build.tcl from boards/zybo/clk_wiz.tcl.
module clk_gen (
    input  wire clk_in,
    output wire clk_a,
    output wire clk_b,
    output wire locked
);
    clk_wiz_0 u_pll (
        .clk_in1 (clk_in),
        .clk_out1(clk_a),
        .clk_out2(clk_b),
        .locked  (locked)
    );
endmodule
